name: Ruff
on: [push, pull_request, workflow_dispatch]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          args: format -v
      - uses: chartboost/ruff-action@v1
        with:
          args: -v
        
